default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: postgres
      password: Rosewood07
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: expensetracker_development

test:
  <<: *default
  database: expensetracker_test

production:
  <<: *default
  database: expensetracker_production